### ISSUE TITLE
Map `base_currency_amount`

### ISSUE THREAD

**Issue by lasuk** [macxred/cashctrl_ledger#30]
#### Description

Our current implementation of `add_ledger()` and `update_ledger()` does not handle the `base_currency_amount` field. All other ledger columns are already mapped correctly or in the course of implementation. For reference, see the definition of the [required and optional columns](https://github.com/macxred/pyledger/blob/1ee680843f9fa771e099a03f19fb9d81c1bc9164/pyledger/ledger_engine.py#L15-L18).

#### Definition

The field `base_currency_amount` does not have a direct equivalent in CashCtrl. To correctly map this field, we need to set the `currencyRate` in CashCtrl such that:

```
currencyRate = amount / base_currency_amount
```

**Comment by AlexTheWizardL** [comment]
Also add "document" field

**Comment by lasuk** [comment]
Implemented as #46 .
