### ISSUE TITLE
Round amount to Currency's Precision

### ISSUE THREAD

**Issue by lasuk** [macxred/cashctrl_ledger#35]
**Background**

CashCtrl stores a transactions' `currencyRate` instead of the `base_currency_amount`, while pyledger and most large accounting systems choose the more flexible approach and store a transactions' `base_currency_amount`.

When mapping to/from CashCtrl, we compute `base_currency_amount = amount * currencyRate`. We currently round this amount to eight digits after the comma. The eight digits are arbitrarily chosen and hard coded.

**Task**

1. Implement `CashCtrlLedger.precision(currency: str) -> float` to fetch the smallest increment for amounts in the specified currency from CashCtrl.
2. Overload `LedgerEngine.round_to_precision` with a vectorized version.
    ```python
    # existing
    LedgerEngine.round_to_precision(amount: float, currency: str) -> float
    # new
    LedgerEngine.round_to_precision(amount: pd.series, currency: pd.series) -> pd.series
    ```
3. Use `LedgerEngine.round_to_precision` instead of `round(..., 8)` to round the `base_currency_amount`. See TODOs in cashctrl_ledger.

**Comment by AlexTheWizardL** [comment]
### General understanding

`CashCtrlLedger.precision(currency: str) -> float`. Precision is the quantity of digits after the comma.
Simple method examples of calculation:
```python
1.02 return -> 0.01
1.0002 return -> 0.0001
1.000002 return -> 0.000001
```

### Following question

- What is the the smallest increment for amounts in the specified currency and where to look for it?
- Is that correct that we need to loop through all transaction `amount` filed and find a value that has the most digits after the comma?
- If the previous question is correct, `CashCtrl` always returns 2 digits after the comma even if more are passed

**Comment by AlexTheWizardL** [comment]
### Correct understanding

`precision(currency: str) -> float` and precision is the smallest increment for amounts in a specified currency is the "smallest unit of currency" or "currency subunit." Example:
```
USD -> smallest is CENT -> 0.01
Mauritania -> Khoums -> 0.00005
Madagascar -> Iraimbilanja -> 0.00005
```

- Define a `_settings` field that will store dict for currencies and precisions. By default empty. Define `set()` and `get()` for it to make it possible for user to provide own precisions.
- `precision(currency: str) -> float` will look up for a currency there, if user haven`t stored something there, return default 0.01
