### ISSUE TITLE
Review collaboration guidelines.

### ISSUE THREAD

**Issue by AlexTheWizardL** [macxred/cashctrl_ledger#53]
### After implementing previous tasks from the milestone we`ll maintain the code style guideline that should be described in the collaboration document.

Contributing file is stored under the [cashctrl_api repo](https://github.com/macxred/cashctrl_api/blob/main/CONTRIBUTING.md). This file is linked in the [Package Development and Contribution](Package Development and Contribution) section in the cashctrl_ledger repo.

This file should be updated with following sections:

- Code style rules
- Common security rules
- Coherence in the code base and docstrings rules
- Navigation in large class definitions rules
- ...

**Comment by lasuk** [comment]
I found below advise by @AlexTheWizardL for working with ChatGPT very helpful.
I suggest to add it to the next version of the collaboration guidelines:
> Save these rules and apply to every code you type for me:
> ```
> [flake8]
> max-line-length = 100
> ignore = D100,D101,D102,D103,D104,D105,D107,D202,D203,D204,D205,D400,D401,D402,D403,D404,D405,D406,D407,D408,D409,D410,D411,D412,D413,D414,E203,W503
> import-order-style = google
> docstring-convention = google
> exclude = .git,__pycache__,.pytest_cache,*.egg-info
> ```
