### ISSUE TITLE
Class for code that violate cashctrl limitations

### ISSUE THREAD

**Issue by AlexTheWizardL** [macxred/cashctrl_ledger#60]
### Proposed names for the new Class with "Hackish" Code:

- [x] `CashCtrlLedgerExtended`

In this example:
- These names indicates that class contains additional, possibly unconventional logic needed for specific integrations.

### List of methods that should be moved to the "hackish" class:

- [ ] `standardize_ledger()`
- [x] `sanitize_ledger()`
- [x] `transitory_account` as property
- [x] `_add_fx_adjustment()`
- [x] `split_multi_currency_transactions()`

### Proposed implementation steps:

1. **Define all `hackish` methods before Lukas vacation.**
2. Create a new class that will inherit `CashCtrlLedger` class.
3. Move `hackish` methods using inheritance pattern in the new class.
4. Adapt test suits to the new hierarchy.
5. Edit classes docstrings.
6. Update `README.md`

**Comment by lasuk** [comment]
Proposal for the class docstring:

```python
class CashCtrlLedger(LedgerEngine):
    """
    Implements the pyledger interface by connecting to the CashCtrl online accounting software.

    See README on https://github.com/macxred/cashctrl_ledger for overview and
    usage examples.
    """
```
